Update cd.yml
added basic tag validation to match vx.x.x

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -43,6 +43,25 @@ jobs:
         
       - uses: actions/checkout@v4
 
+      - name: Validate entered release tag
+        id: check-tag
+        run: |
+            if [[ ${{ env.IMAGE_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ }} ]]; then
+                echo "match=true" >> $GITHUB_OUTPUT
+            fi
+            
+      - name: Valid tag outcome
+        if: steps.check-tag.outputs.match == "true"
+        run: |
+            echo "Release tag ${{ steps.check-tag.outputs.match }} is valid
+            
+      - name: Parse validation results
+        if: ${{ !steps.check-tag.outputs.match == "true" }}
+        run: |
+            echo "Release tag ${{ steps.check-tag.outputs.match }} is invalid
+            exit 1
+      
+
       - name: use non-prod values
         if: github.ref == 'refs/heads/develop'
         #  sed -i "s/<IMAGE_TAG>/v3.0.0.7/g" ./skaffold.yaml
