remove branch protection rule

diff --git a/.github/workflows/ci_tf.yml b/.github/workflows/ci_tf.yml
--- a/.github/workflows/ci_tf.yml
+++ b/.github/workflows/ci_tf.yml
@@ -6,6 +6,7 @@ on:
   #pull_request:
   #  branches:
   #    - develop
+  #    - main
   #  paths:
   #    - 'terraform/**
   workflow_dispatch:
@@ -16,8 +17,7 @@ jobs:
     steps:
       - run: echo "This job is automatically triggered by a ${{ github.event_name }} event."
 
-  terraform-ci:
-    name: Terraform CI
+  terraform-tflint-validate:
     runs-on: ubuntu-latest
     defaults:
       run:
@@ -26,40 +26,66 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v4.1.7
-
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v4.0.2
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ${{ vars.AWS_REGION }}
-
       - name: Setup Terraform
         uses: hashicorp/setup-terraform@v3
-
-      # To check that this preparation steps in the job workflow are running
-      # properly up to now
 
       - name: Check the tf code for programmatic and stylistic errors
         uses: terraform-linters/setup-tflint@v3
         with:
           tflint_version: latest
-
       - name: Show the version installed
         run: tflint --version
-
       - name: Init TFLinit
         run: tflint --init
-
       - name: Run TFLint
         run: tflint -f compact
 
       - name: Terraform Init
         run: terraform init
-
-      - name: Clean up the spacing format of the tf code
+      - name: Clean up the spacing format
         run: terraform fmt -check
         continue-on-error: true
-
       - name: Terraform Validate
         run: terraform validate -no-color
+
+  terraform-checkov:
+    runs-on: ubuntu-latest
+    defaults:
+      run:
+        working-directory: terraform
+
+    steps:
+    - name: Checkout
+      uses: actions/checkout@v3
+    - name: Set up Python 3.12
+      uses: actions/setup-python@v4
+      with:
+        python-version: 3.12
+    - name: Checkov
+      uses: bridgecrewio/checkov-action@master
+      with:
+        framework: terraform
+        # This will add both a CLI output to the console and create a results.sarif file
+        output_format: cli,sarif
+        output_file_path: console,checkov.sarif
+        skip_check: CKV_AWS_56,CKV_AWS_55,CKV_AWS_54,CKV_AWS_53,CKV2_AWS_62,CKV2_AWS_65,CKV_AWS_144,CKV2_AWS_61,CKV2_AWS_6,CKV_AWS_18
+        quiet: true # display only failed checks
+
+    - name: Upload SARIF file
+      uses: github/codeql-action/upload-sarif@v2
+      # Results are generated only on a success or failure
+      # this is required since GitHub by default won't run 
+      # the next step when the previous one has failed. 
+      # Security checks that do not pass will 'fail'.
+      # An alternative is to add `continue-on-error: true` 
+      # to the previous step
+      # Or 'soft_fail: true' to checkov.
+      if: success() || failure()
+      with:
+        sarif_file: checkov.sarif
